services:
  app:
    depends_on:
      - db
    ports:
      - "8080:3000"
    restart: always
    environment:
      REACT_APP_NORSKEREKORDERWCA_KEY: ${REACT_APP_NORSKEREKORDERWCA_KEY}
      REACT_APP_NORSKEREKORDERNONWCA_KEY: ${REACT_APP_NORSKEREKORDERNONWCA_KEY}
      WCA_OAUTH_CLIENT_ID: ${WCA_OAUTH_CLIENT_ID}
      WCA_OAUTH_SECRET: ${WCA_OAUTH_SECRET}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      JWT_SECRET: ${JWT_SECRET}
      TOKEN_ENCRYPTION_SECRET: ${TOKEN_ENCRYPTION_SECRET}
    build: .

  db:
    image: postgres:18
    restart: always
    volumes:
      - db_prod:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db_prod:
